# -*- coding: utf-8 -*-
"""Tharindu(11267).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1in5Um4z7kbAeTQ8LXk6AYHw6wPEDoCFQ
"""

# ============================================================
#  Fast Food Nutritional Analysis — DSA-609 Case Study
#  Dataset: Fast Food Calories (Tidy Tuesday, 2018)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# ============================================================
#  LOAD THE DATA
# ============================================================
df = pd.read_csv('fastfood_calories.csv')
df.head()

df.shape
# (509, 16)

# ============================================================
#  CLEAN AND PREPROCESS DATA
# ============================================================

# 1. Remove unnecessary first column
df = df.drop(columns=['Unnamed: 0'], errors='ignore')

# 2. Standardize restaurant names
df['restaurant'] = df['restaurant'].str.strip()
df['restaurant'] = df['restaurant'].replace({
    'Mcdonalds':   'McDonalds',
    'Chick Fil-A': 'Chick-fil-A',
    'Arbys':       "Arby's",
    'Dairy Queen': 'Dairy Queen',
    'Burger King': 'Burger King',
    'Subway':      'Subway',
    'Taco Bell':   'Taco Bell',
    'Sonic':       'Sonic'
})

# 3. Clean item names
df['item'] = df['item'].str.strip()

# 4. Handle missing values (NA)
numeric_cols = ['calories', 'cal_fat', 'total_fat', 'sat_fat', 'trans_fat',
                'cholesterol', 'sodium', 'total_carb', 'fiber', 'sugar',
                'protein', 'vit_a', 'vit_c', 'calcium']
df[numeric_cols] = df[numeric_cols].replace('NA', pd.NA)

# Create a cleaned version of the dataset
cleaned_df = df.copy()

# Check for missing values
print("Missing values per column:")
print(cleaned_df.isnull().sum())

cleaned_df.fillna(0, inplace=True)

# Check for missing values again
print("Missing values per column:")
print(cleaned_df.isnull().sum())

# 5. Convert columns to numeric type
cleaned_df[numeric_cols] = cleaned_df[numeric_cols].apply(pd.to_numeric)

# 6. Check for duplicates
print(f"Duplicate rows: {cleaned_df.duplicated().sum()}")
cleaned_df.drop_duplicates(inplace=True)
print(f"Duplicate rows: {cleaned_df.duplicated().sum()}")

cleaned_df.shape
# (509, 16)

# ============================================================
#  EXPLORATORY DATA ANALYSIS
# ============================================================

# 1. Basic statistics
print("\nBasic statistics:")
print(cleaned_df[numeric_cols].describe())

# 2. Calorie Distribution Analysis
plt.figure(figsize=(10, 6))
sns.histplot(data=cleaned_df, x='calories', bins=30, kde=True)
plt.title("Distribution of Calories in Fast Food Items")
plt.xlabel("Calories")
plt.ylabel("Frequency")
plt.show()

# Boxplot of calories
plt.figure(figsize=(10, 6))
sns.boxplot(data=cleaned_df['calories'], orient='h')
plt.title("Boxplot of Calories")
plt.show()

# 3. Calories by Chain
avg_calories = cleaned_df.groupby('restaurant')['calories'].mean().sort_values()
avg_calories

avg_calories.plot(kind='bar', figsize=(10, 5))
plt.title("Average Calories per Restaurant")
plt.ylabel("Calories")
plt.show()

# 4. Principal Component Analysis (PCA)
# Select relevant nutritional variables (excluding categorical variables)
nutrition_cols = ['total_fat', 'cholesterol', 'sodium', 'total_carb',
                  'protein', 'vit_a', 'vit_c', 'calcium']

# Create a subset with only nutritional data
nutrition_df = cleaned_df[nutrition_cols]

# Standardize the data (important for PCA)
scaler = StandardScaler()
nutrition_scaled = scaler.fit_transform(nutrition_df)

# Perform PCA
pca = PCA()
principal_components = pca.fit_transform(nutrition_scaled)

# Eigenvalues (explained variance)
eigenvalues = pca.explained_variance_
print("Eigenvalues (Explained Variance):")
print(eigenvalues)
print('\n')

# Calculate total variation
total_variation = sum(eigenvalues)
print(f"Total Variation: {total_variation:.4f}")

# Scree plot
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(eigenvalues)+1), eigenvalues, 'bo-', linewidth=2)
plt.title('Scree Plot')
plt.xlabel('Principal Component')
plt.ylabel('Eigenvalue (Explained Variance)')
plt.axhline(y=1, color='r', linestyle='--')   # Kaiser criterion line
plt.grid()
plt.show()

# Eigenvectors (loadings)
eigenvectors = pca.components_
print("\nEigenvectors (Principal Components Loadings):")
for i, component in enumerate(eigenvectors):
    print(f"\nPrincipal Component {i+1}:")
    print(pd.Series(component, index=nutrition_cols))

# Calculate proportion of variation for each component
proportions = eigenvalues / total_variation
print("\nProportion of Total Variation for Each Principal Component:")
for i, prop in enumerate(proportions):
    print(f"PC{i+1}: {prop:.4f} ({prop*100:.2f}%)")

# Cumulative proportion
cumulative_prop = np.cumsum(proportions)
print("\nCumulative Proportion of Total Variation:")
for i, cum_prop in enumerate(cumulative_prop):
    print(f"PC1 to PC{i+1}: {cum_prop:.4f} ({cum_prop*100:.2f}%)")

# Restaurant-wise Data Balance
print(cleaned_df["restaurant"].value_counts())

# Count plot for restaurant distribution
plt.figure(figsize=(12, 6))
sns.countplot(data=cleaned_df, x='restaurant',
              order=cleaned_df['restaurant'].value_counts().index)
plt.xticks(rotation=45)
plt.xlabel("Restaurant")
plt.ylabel("Count")
plt.title("Number of Items per Restaurant")
plt.show()

# Correlation heatmap
numeric_cols_corr = ['calories', 'protein', 'sodium', 'total_fat']
plt.figure(figsize=(12, 8))
sns.heatmap(cleaned_df[numeric_cols_corr].corr(), annot=True,
            cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title("Feature Correlation Heatmap")
plt.show()

# Restaurant-wise nutrient comparison
data = cleaned_df.copy()
data['sodium'] = data['sodium'] / 1000
restaurant_stats = data.groupby('restaurant')[['protein', 'sodium', 'total_fat']].mean()
print(restaurant_stats)

plt.figure(figsize=(12, 6))
restaurant_stats.plot(kind='bar', stacked=False)
plt.title('Restaurant-wise Comparison of Nutrients')
plt.ylabel('Amount (g)')
plt.xticks(rotation=45)
plt.legend(title='Nutrients')
plt.tight_layout()
plt.show()

# Scatter plots: Calories vs Fat, Sodium, Protein
plt.figure(figsize=(18, 5))

plt.subplot(1, 3, 1)
sns.scatterplot(x='total_fat', y='calories', data=cleaned_df,
                hue='restaurant', palette='viridis', alpha=0.7)
plt.title('Calories vs Total Fat')
plt.xlabel('total_fat')
plt.ylabel('Total Calories')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

plt.subplot(1, 3, 2)
sns.scatterplot(x='sodium', y='calories', data=cleaned_df,
                hue='restaurant', palette='viridis', alpha=0.7)
plt.title('Calories vs Sodium')
plt.xlabel('Sodium (mg)')
plt.ylabel('Total Calories')
plt.legend().remove()

plt.subplot(1, 3, 3)
sns.scatterplot(x='protein', y='calories', data=cleaned_df,
                hue='restaurant', palette='viridis', alpha=0.7)
plt.title('Calories vs Protein')
plt.xlabel('Protein (g)')
plt.ylabel('Total Calories')
plt.legend().remove()

plt.tight_layout()
plt.show()

# ============================================================
#  ML/AI METHODS
# ============================================================

# Select features and target
X = cleaned_df[['total_fat', 'cholesterol', 'sodium', 'total_carb',
                'protein', 'vit_a', 'vit_c', 'calcium']]
y = cleaned_df['calories']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=88)

# ── Linear Regression ──────────────────────────────────────
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_pred = lr_model.predict(X_test)

print("\nLinear Regression Performance:")
print("MAE:", mean_absolute_error(y_test, lr_pred))
print("MSE:", mean_squared_error(y_test, lr_pred))
print("R2 Score:", r2_score(y_test, lr_pred))

plt.figure(figsize=(7, 5))
plt.scatter(y_test, lr_pred, alpha=0.6, color='steelblue', label='Predictions')
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()], 'r--', label='Perfect fit')
plt.xlabel("Actual Calories")
plt.ylabel("Predicted Calories")
plt.title("Linear Regression: Actual vs Predicted")
plt.legend()
plt.show()

# ── Random Forest Regressor ────────────────────────────────
rf_model = RandomForestRegressor(n_estimators=100, random_state=88)
rf_model.fit(X_train, y_train)
rf_pred = rf_model.predict(X_test)

print("\nRandom Forest Performance:")
print("MAE:", mean_absolute_error(y_test, rf_pred))
print("MSE:", mean_squared_error(y_test, rf_pred))
print("R2 Score:", r2_score(y_test, rf_pred))

plt.figure(figsize=(7, 5))
plt.scatter(y_test, rf_pred, alpha=0.6, color='darkorange', label='Predictions')
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()], 'r--', label='Perfect fit')
plt.xlabel("Actual Calories")
plt.ylabel("Predicted Calories")
plt.title("Random Forest: Actual vs Predicted")
plt.legend()
plt.show()

# ── Neural Network ─────────────────────────────────────────
# Scale features for neural network
scaler2 = StandardScaler()
X_train_scaled = scaler2.fit_transform(X_train)
X_test_scaled  = scaler2.transform(X_test)

nn_model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.2),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')
])

nn_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
history = nn_model.fit(
    X_train_scaled, y_train,
    epochs=100,
    batch_size=16,
    validation_data=(X_test_scaled, y_test),
    verbose=1
)

nn_pred = nn_model.predict(X_test_scaled).flatten()

print("\nNeural Network Performance:")
print("MAE:", mean_absolute_error(y_test, nn_pred))
print("MSE:", mean_squared_error(y_test, nn_pred))
print("R2 Score:", r2_score(y_test, nn_pred))

# Plot predictions
plt.figure(figsize=(7, 5))
plt.scatter(y_test, nn_pred, alpha=0.6, color='mediumseagreen', label='Predictions')
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()], 'r--', label='Perfect fit')
plt.xlabel("Actual Calories")
plt.ylabel("Predicted Calories")
plt.title("Neural Network: Actual vs Predicted")
plt.legend()
plt.show()

# Training loss curve
plt.figure(figsize=(8, 5))
plt.plot(history.history['loss'],     label='Train Loss', color='steelblue')
plt.plot(history.history['val_loss'], label='Val Loss',   color='coral')
plt.title("Neural Network Training Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss (MSE)")
plt.legend()
plt.grid(True)
plt.show()

# ── Model Comparison Summary ───────────────────────────────
print("\n=== MODEL COMPARISON SUMMARY ===")
print(f"{'Metric':<12} {'Linear Reg':>14} {'Random Forest':>15} {'Neural Net':>12} {'Best':>18}")
print("-" * 75)
print(f"{'R2 Score':<12} {r2_score(y_test, lr_pred):>14.4f} {r2_score(y_test, rf_pred):>15.4f} {r2_score(y_test, nn_pred):>12.4f} {'Linear Regression':>18}")
print(f"{'MAE':<12} {mean_absolute_error(y_test, lr_pred):>14.2f} {mean_absolute_error(y_test, rf_pred):>15.2f} {mean_absolute_error(y_test, nn_pred):>12.2f} {'Linear Regression':>18}")
print(f"{'MSE':<12} {mean_squared_error(y_test, lr_pred):>14.2f} {mean_squared_error(y_test, rf_pred):>15.2f} {mean_squared_error(y_test, nn_pred):>12.2f} {'Linear Regression':>18}")